package x5;

import android.R;

/* compiled from: MyApplication */
/* loaded from: classes2.dex */
public abstract class a {

    /* renamed from: a, reason: collision with root package name */
    public static final int[] f11018a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.expanded, com.p2elite.brtv2.R.attr.liftOnScroll, com.p2elite.brtv2.R.attr.liftOnScrollTargetViewId, com.p2elite.brtv2.R.attr.statusBarForeground};

    /* renamed from: b, reason: collision with root package name */
    public static final int[] f11020b = {com.p2elite.brtv2.R.attr.layout_scrollEffect, com.p2elite.brtv2.R.attr.layout_scrollFlags, com.p2elite.brtv2.R.attr.layout_scrollInterpolator};

    /* renamed from: c, reason: collision with root package name */
    public static final int[] f11022c = {com.p2elite.brtv2.R.attr.backgroundColor, com.p2elite.brtv2.R.attr.badgeGravity, com.p2elite.brtv2.R.attr.badgeRadius, com.p2elite.brtv2.R.attr.badgeTextColor, com.p2elite.brtv2.R.attr.badgeWidePadding, com.p2elite.brtv2.R.attr.badgeWithTextRadius, com.p2elite.brtv2.R.attr.horizontalOffset, com.p2elite.brtv2.R.attr.horizontalOffsetWithText, com.p2elite.brtv2.R.attr.maxCharacterCount, com.p2elite.brtv2.R.attr.number, com.p2elite.brtv2.R.attr.verticalOffset, com.p2elite.brtv2.R.attr.verticalOffsetWithText};
    public static final int[] d = {R.attr.indeterminate, com.p2elite.brtv2.R.attr.hideAnimationBehavior, com.p2elite.brtv2.R.attr.indicatorColor, com.p2elite.brtv2.R.attr.minHideDelay, com.p2elite.brtv2.R.attr.showAnimationBehavior, com.p2elite.brtv2.R.attr.showDelay, com.p2elite.brtv2.R.attr.trackColor, com.p2elite.brtv2.R.attr.trackCornerRadius, com.p2elite.brtv2.R.attr.trackThickness};

    /* renamed from: e, reason: collision with root package name */
    public static final int[] f11025e = {com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.fabAlignmentMode, com.p2elite.brtv2.R.attr.fabAnimationMode, com.p2elite.brtv2.R.attr.fabCradleMargin, com.p2elite.brtv2.R.attr.fabCradleRoundedCornerRadius, com.p2elite.brtv2.R.attr.fabCradleVerticalOffset, com.p2elite.brtv2.R.attr.hideOnScroll, com.p2elite.brtv2.R.attr.navigationIconTint, com.p2elite.brtv2.R.attr.paddingBottomSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingLeftSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingRightSystemWindowInsets};
    public static final int[] f = {R.attr.minHeight, com.p2elite.brtv2.R.attr.itemHorizontalTranslationEnabled};

    /* renamed from: g, reason: collision with root package name */
    public static final int[] f11026g = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.behavior_draggable, com.p2elite.brtv2.R.attr.behavior_expandedOffset, com.p2elite.brtv2.R.attr.behavior_fitToContents, com.p2elite.brtv2.R.attr.behavior_halfExpandedRatio, com.p2elite.brtv2.R.attr.behavior_hideable, com.p2elite.brtv2.R.attr.behavior_peekHeight, com.p2elite.brtv2.R.attr.behavior_saveFlags, com.p2elite.brtv2.R.attr.behavior_skipCollapsed, com.p2elite.brtv2.R.attr.gestureInsetBottomIgnored, com.p2elite.brtv2.R.attr.marginLeftSystemWindowInsets, com.p2elite.brtv2.R.attr.marginRightSystemWindowInsets, com.p2elite.brtv2.R.attr.marginTopSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingBottomSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingLeftSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingRightSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingTopSystemWindowInsets, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay};

    /* renamed from: h, reason: collision with root package name */
    public static final int[] f11027h = {R.attr.minWidth, R.attr.minHeight, com.p2elite.brtv2.R.attr.cardBackgroundColor, com.p2elite.brtv2.R.attr.cardCornerRadius, com.p2elite.brtv2.R.attr.cardElevation, com.p2elite.brtv2.R.attr.cardMaxElevation, com.p2elite.brtv2.R.attr.cardPreventCornerOverlap, com.p2elite.brtv2.R.attr.cardUseCompatPadding, com.p2elite.brtv2.R.attr.contentPadding, com.p2elite.brtv2.R.attr.contentPaddingBottom, com.p2elite.brtv2.R.attr.contentPaddingLeft, com.p2elite.brtv2.R.attr.contentPaddingRight, com.p2elite.brtv2.R.attr.contentPaddingTop};

    /* renamed from: i, reason: collision with root package name */
    public static final int[] f11028i = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, com.p2elite.brtv2.R.attr.checkedIcon, com.p2elite.brtv2.R.attr.checkedIconEnabled, com.p2elite.brtv2.R.attr.checkedIconTint, com.p2elite.brtv2.R.attr.checkedIconVisible, com.p2elite.brtv2.R.attr.chipBackgroundColor, com.p2elite.brtv2.R.attr.chipCornerRadius, com.p2elite.brtv2.R.attr.chipEndPadding, com.p2elite.brtv2.R.attr.chipIcon, com.p2elite.brtv2.R.attr.chipIconEnabled, com.p2elite.brtv2.R.attr.chipIconSize, com.p2elite.brtv2.R.attr.chipIconTint, com.p2elite.brtv2.R.attr.chipIconVisible, com.p2elite.brtv2.R.attr.chipMinHeight, com.p2elite.brtv2.R.attr.chipMinTouchTargetSize, com.p2elite.brtv2.R.attr.chipStartPadding, com.p2elite.brtv2.R.attr.chipStrokeColor, com.p2elite.brtv2.R.attr.chipStrokeWidth, com.p2elite.brtv2.R.attr.chipSurfaceColor, com.p2elite.brtv2.R.attr.closeIcon, com.p2elite.brtv2.R.attr.closeIconEnabled, com.p2elite.brtv2.R.attr.closeIconEndPadding, com.p2elite.brtv2.R.attr.closeIconSize, com.p2elite.brtv2.R.attr.closeIconStartPadding, com.p2elite.brtv2.R.attr.closeIconTint, com.p2elite.brtv2.R.attr.closeIconVisible, com.p2elite.brtv2.R.attr.ensureMinTouchTargetSize, com.p2elite.brtv2.R.attr.hideMotionSpec, com.p2elite.brtv2.R.attr.iconEndPadding, com.p2elite.brtv2.R.attr.iconStartPadding, com.p2elite.brtv2.R.attr.rippleColor, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.showMotionSpec, com.p2elite.brtv2.R.attr.textEndPadding, com.p2elite.brtv2.R.attr.textStartPadding};

    /* renamed from: j, reason: collision with root package name */
    public static final int[] f11029j = {com.p2elite.brtv2.R.attr.checkedChip, com.p2elite.brtv2.R.attr.chipSpacing, com.p2elite.brtv2.R.attr.chipSpacingHorizontal, com.p2elite.brtv2.R.attr.chipSpacingVertical, com.p2elite.brtv2.R.attr.selectionRequired, com.p2elite.brtv2.R.attr.singleLine, com.p2elite.brtv2.R.attr.singleSelection};

    /* renamed from: k, reason: collision with root package name */
    public static final int[] f11030k = {com.p2elite.brtv2.R.attr.indicatorDirectionCircular, com.p2elite.brtv2.R.attr.indicatorInset, com.p2elite.brtv2.R.attr.indicatorSize};

    /* renamed from: l, reason: collision with root package name */
    public static final int[] f11031l = {com.p2elite.brtv2.R.attr.clockFaceBackgroundColor, com.p2elite.brtv2.R.attr.clockNumberTextColor};

    /* renamed from: m, reason: collision with root package name */
    public static final int[] f11032m = {com.p2elite.brtv2.R.attr.clockHandColor, com.p2elite.brtv2.R.attr.materialCircleRadius, com.p2elite.brtv2.R.attr.selectorSize};

    /* renamed from: n, reason: collision with root package name */
    public static final int[] f11033n = {com.p2elite.brtv2.R.attr.collapsedTitleGravity, com.p2elite.brtv2.R.attr.collapsedTitleTextAppearance, com.p2elite.brtv2.R.attr.collapsedTitleTextColor, com.p2elite.brtv2.R.attr.contentScrim, com.p2elite.brtv2.R.attr.expandedTitleGravity, com.p2elite.brtv2.R.attr.expandedTitleMargin, com.p2elite.brtv2.R.attr.expandedTitleMarginBottom, com.p2elite.brtv2.R.attr.expandedTitleMarginEnd, com.p2elite.brtv2.R.attr.expandedTitleMarginStart, com.p2elite.brtv2.R.attr.expandedTitleMarginTop, com.p2elite.brtv2.R.attr.expandedTitleTextAppearance, com.p2elite.brtv2.R.attr.expandedTitleTextColor, com.p2elite.brtv2.R.attr.extraMultilineHeightEnabled, com.p2elite.brtv2.R.attr.forceApplySystemWindowInsetTop, com.p2elite.brtv2.R.attr.maxLines, com.p2elite.brtv2.R.attr.scrimAnimationDuration, com.p2elite.brtv2.R.attr.scrimVisibleHeightTrigger, com.p2elite.brtv2.R.attr.statusBarScrim, com.p2elite.brtv2.R.attr.title, com.p2elite.brtv2.R.attr.titleCollapseMode, com.p2elite.brtv2.R.attr.titleEnabled, com.p2elite.brtv2.R.attr.titlePositionInterpolator, com.p2elite.brtv2.R.attr.toolbarId};

    /* renamed from: o, reason: collision with root package name */
    public static final int[] f11034o = {com.p2elite.brtv2.R.attr.layout_collapseMode, com.p2elite.brtv2.R.attr.layout_collapseParallaxMultiplier};

    /* renamed from: p, reason: collision with root package name */
    public static final int[] f11035p = {com.p2elite.brtv2.R.attr.collapsedSize, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.extendMotionSpec, com.p2elite.brtv2.R.attr.hideMotionSpec, com.p2elite.brtv2.R.attr.showMotionSpec, com.p2elite.brtv2.R.attr.shrinkMotionSpec};

    /* renamed from: q, reason: collision with root package name */
    public static final int[] f11036q = {com.p2elite.brtv2.R.attr.behavior_autoHide, com.p2elite.brtv2.R.attr.behavior_autoShrink};

    /* renamed from: r, reason: collision with root package name */
    public static final int[] f11037r = {R.attr.enabled, com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.backgroundTintMode, com.p2elite.brtv2.R.attr.borderWidth, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.ensureMinTouchTargetSize, com.p2elite.brtv2.R.attr.fabCustomSize, com.p2elite.brtv2.R.attr.fabSize, com.p2elite.brtv2.R.attr.hideMotionSpec, com.p2elite.brtv2.R.attr.hoveredFocusedTranslationZ, com.p2elite.brtv2.R.attr.maxImageSize, com.p2elite.brtv2.R.attr.pressedTranslationZ, com.p2elite.brtv2.R.attr.rippleColor, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.showMotionSpec, com.p2elite.brtv2.R.attr.useCompatPadding};

    /* renamed from: s, reason: collision with root package name */
    public static final int[] f11038s = {com.p2elite.brtv2.R.attr.behavior_autoHide};

    /* renamed from: t, reason: collision with root package name */
    public static final int[] f11039t = {com.p2elite.brtv2.R.attr.itemSpacing, com.p2elite.brtv2.R.attr.lineSpacing};

    /* renamed from: u, reason: collision with root package name */
    public static final int[] f11040u = {R.attr.foreground, R.attr.foregroundGravity, com.p2elite.brtv2.R.attr.foregroundInsidePadding};

    /* renamed from: v, reason: collision with root package name */
    public static final int[] f11041v = {com.p2elite.brtv2.R.attr.marginLeftSystemWindowInsets, com.p2elite.brtv2.R.attr.marginRightSystemWindowInsets, com.p2elite.brtv2.R.attr.marginTopSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingBottomSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingLeftSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingRightSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingTopSystemWindowInsets};

    /* renamed from: w, reason: collision with root package name */
    public static final int[] f11042w = {com.p2elite.brtv2.R.attr.indeterminateAnimationType, com.p2elite.brtv2.R.attr.indicatorDirectionLinear};

    /* renamed from: x, reason: collision with root package name */
    public static final int[] f11043x = {R.attr.inputType, com.p2elite.brtv2.R.attr.simpleItemLayout, com.p2elite.brtv2.R.attr.simpleItems};

    /* renamed from: y, reason: collision with root package name */
    public static final int[] f11044y = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.backgroundTintMode, com.p2elite.brtv2.R.attr.cornerRadius, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.icon, com.p2elite.brtv2.R.attr.iconGravity, com.p2elite.brtv2.R.attr.iconPadding, com.p2elite.brtv2.R.attr.iconSize, com.p2elite.brtv2.R.attr.iconTint, com.p2elite.brtv2.R.attr.iconTintMode, com.p2elite.brtv2.R.attr.rippleColor, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.strokeColor, com.p2elite.brtv2.R.attr.strokeWidth};

    /* renamed from: z, reason: collision with root package name */
    public static final int[] f11045z = {com.p2elite.brtv2.R.attr.checkedButton, com.p2elite.brtv2.R.attr.selectionRequired, com.p2elite.brtv2.R.attr.singleSelection};
    public static final int[] A = {R.attr.windowFullscreen, com.p2elite.brtv2.R.attr.dayInvalidStyle, com.p2elite.brtv2.R.attr.daySelectedStyle, com.p2elite.brtv2.R.attr.dayStyle, com.p2elite.brtv2.R.attr.dayTodayStyle, com.p2elite.brtv2.R.attr.nestedScrollable, com.p2elite.brtv2.R.attr.rangeFillColor, com.p2elite.brtv2.R.attr.yearSelectedStyle, com.p2elite.brtv2.R.attr.yearStyle, com.p2elite.brtv2.R.attr.yearTodayStyle};
    public static final int[] B = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, com.p2elite.brtv2.R.attr.itemFillColor, com.p2elite.brtv2.R.attr.itemShapeAppearance, com.p2elite.brtv2.R.attr.itemShapeAppearanceOverlay, com.p2elite.brtv2.R.attr.itemStrokeColor, com.p2elite.brtv2.R.attr.itemStrokeWidth, com.p2elite.brtv2.R.attr.itemTextColor};
    public static final int[] C = {R.attr.checkable, com.p2elite.brtv2.R.attr.cardForegroundColor, com.p2elite.brtv2.R.attr.checkedIcon, com.p2elite.brtv2.R.attr.checkedIconGravity, com.p2elite.brtv2.R.attr.checkedIconMargin, com.p2elite.brtv2.R.attr.checkedIconSize, com.p2elite.brtv2.R.attr.checkedIconTint, com.p2elite.brtv2.R.attr.rippleColor, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.state_dragged, com.p2elite.brtv2.R.attr.strokeColor, com.p2elite.brtv2.R.attr.strokeWidth};
    public static final int[] D = {com.p2elite.brtv2.R.attr.buttonTint, com.p2elite.brtv2.R.attr.centerIfNoTextEnabled, com.p2elite.brtv2.R.attr.useMaterialThemeColors};
    public static final int[] E = {com.p2elite.brtv2.R.attr.dividerColor, com.p2elite.brtv2.R.attr.dividerInsetEnd, com.p2elite.brtv2.R.attr.dividerInsetStart, com.p2elite.brtv2.R.attr.dividerThickness, com.p2elite.brtv2.R.attr.lastItemDecorated};
    public static final int[] F = {com.p2elite.brtv2.R.attr.buttonTint, com.p2elite.brtv2.R.attr.useMaterialThemeColors};
    public static final int[] G = {com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay};
    public static final int[] H = {R.attr.letterSpacing, R.attr.lineHeight, com.p2elite.brtv2.R.attr.lineHeight};
    public static final int[] I = {R.attr.textAppearance, R.attr.lineHeight, com.p2elite.brtv2.R.attr.lineHeight};
    public static final int[] J = {com.p2elite.brtv2.R.attr.logoAdjustViewBounds, com.p2elite.brtv2.R.attr.logoScaleType, com.p2elite.brtv2.R.attr.navigationIconTint, com.p2elite.brtv2.R.attr.subtitleCentered, com.p2elite.brtv2.R.attr.titleCentered};
    public static final int[] K = {R.attr.height, R.attr.width, R.attr.color, com.p2elite.brtv2.R.attr.marginHorizontal, com.p2elite.brtv2.R.attr.shapeAppearance};
    public static final int[] L = {com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.itemActiveIndicatorStyle, com.p2elite.brtv2.R.attr.itemBackground, com.p2elite.brtv2.R.attr.itemIconSize, com.p2elite.brtv2.R.attr.itemIconTint, com.p2elite.brtv2.R.attr.itemPaddingBottom, com.p2elite.brtv2.R.attr.itemPaddingTop, com.p2elite.brtv2.R.attr.itemRippleColor, com.p2elite.brtv2.R.attr.itemTextAppearanceActive, com.p2elite.brtv2.R.attr.itemTextAppearanceInactive, com.p2elite.brtv2.R.attr.itemTextColor, com.p2elite.brtv2.R.attr.labelVisibilityMode, com.p2elite.brtv2.R.attr.menu};
    public static final int[] M = {com.p2elite.brtv2.R.attr.headerLayout, com.p2elite.brtv2.R.attr.itemMinHeight, com.p2elite.brtv2.R.attr.menuGravity, com.p2elite.brtv2.R.attr.paddingBottomSystemWindowInsets, com.p2elite.brtv2.R.attr.paddingTopSystemWindowInsets};
    public static final int[] N = {R.attr.layout_gravity, R.attr.background, R.attr.fitsSystemWindows, R.attr.maxWidth, com.p2elite.brtv2.R.attr.bottomInsetScrimEnabled, com.p2elite.brtv2.R.attr.dividerInsetEnd, com.p2elite.brtv2.R.attr.dividerInsetStart, com.p2elite.brtv2.R.attr.drawerLayoutCornerSize, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.headerLayout, com.p2elite.brtv2.R.attr.itemBackground, com.p2elite.brtv2.R.attr.itemHorizontalPadding, com.p2elite.brtv2.R.attr.itemIconPadding, com.p2elite.brtv2.R.attr.itemIconSize, com.p2elite.brtv2.R.attr.itemIconTint, com.p2elite.brtv2.R.attr.itemMaxLines, com.p2elite.brtv2.R.attr.itemRippleColor, com.p2elite.brtv2.R.attr.itemShapeAppearance, com.p2elite.brtv2.R.attr.itemShapeAppearanceOverlay, com.p2elite.brtv2.R.attr.itemShapeFillColor, com.p2elite.brtv2.R.attr.itemShapeInsetBottom, com.p2elite.brtv2.R.attr.itemShapeInsetEnd, com.p2elite.brtv2.R.attr.itemShapeInsetStart, com.p2elite.brtv2.R.attr.itemShapeInsetTop, com.p2elite.brtv2.R.attr.itemTextAppearance, com.p2elite.brtv2.R.attr.itemTextColor, com.p2elite.brtv2.R.attr.itemVerticalPadding, com.p2elite.brtv2.R.attr.menu, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.subheaderColor, com.p2elite.brtv2.R.attr.subheaderInsetEnd, com.p2elite.brtv2.R.attr.subheaderInsetStart, com.p2elite.brtv2.R.attr.subheaderTextAppearance, com.p2elite.brtv2.R.attr.topInsetScrimEnabled};
    public static final int[] O = {com.p2elite.brtv2.R.attr.materialCircleRadius};
    public static final int[] P = {com.p2elite.brtv2.R.attr.minSeparation, com.p2elite.brtv2.R.attr.values};
    public static final int[] Q = {com.p2elite.brtv2.R.attr.insetForeground};
    public static final int[] R = {com.p2elite.brtv2.R.attr.behavior_overlapTop};
    public static final int[] S = {com.p2elite.brtv2.R.attr.cornerFamily, com.p2elite.brtv2.R.attr.cornerFamilyBottomLeft, com.p2elite.brtv2.R.attr.cornerFamilyBottomRight, com.p2elite.brtv2.R.attr.cornerFamilyTopLeft, com.p2elite.brtv2.R.attr.cornerFamilyTopRight, com.p2elite.brtv2.R.attr.cornerSize, com.p2elite.brtv2.R.attr.cornerSizeBottomLeft, com.p2elite.brtv2.R.attr.cornerSizeBottomRight, com.p2elite.brtv2.R.attr.cornerSizeTopLeft, com.p2elite.brtv2.R.attr.cornerSizeTopRight};
    public static final int[] T = {com.p2elite.brtv2.R.attr.contentPadding, com.p2elite.brtv2.R.attr.contentPaddingBottom, com.p2elite.brtv2.R.attr.contentPaddingEnd, com.p2elite.brtv2.R.attr.contentPaddingLeft, com.p2elite.brtv2.R.attr.contentPaddingRight, com.p2elite.brtv2.R.attr.contentPaddingStart, com.p2elite.brtv2.R.attr.contentPaddingTop, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.strokeColor, com.p2elite.brtv2.R.attr.strokeWidth};
    public static final int[] U = {R.attr.enabled, R.attr.value, R.attr.stepSize, R.attr.valueFrom, R.attr.valueTo, com.p2elite.brtv2.R.attr.haloColor, com.p2elite.brtv2.R.attr.haloRadius, com.p2elite.brtv2.R.attr.labelBehavior, com.p2elite.brtv2.R.attr.labelStyle, com.p2elite.brtv2.R.attr.thumbColor, com.p2elite.brtv2.R.attr.thumbElevation, com.p2elite.brtv2.R.attr.thumbRadius, com.p2elite.brtv2.R.attr.thumbStrokeColor, com.p2elite.brtv2.R.attr.thumbStrokeWidth, com.p2elite.brtv2.R.attr.tickColor, com.p2elite.brtv2.R.attr.tickColorActive, com.p2elite.brtv2.R.attr.tickColorInactive, com.p2elite.brtv2.R.attr.tickVisible, com.p2elite.brtv2.R.attr.trackColor, com.p2elite.brtv2.R.attr.trackColorActive, com.p2elite.brtv2.R.attr.trackColorInactive, com.p2elite.brtv2.R.attr.trackHeight};
    public static final int[] V = {R.attr.maxWidth, com.p2elite.brtv2.R.attr.actionTextColorAlpha, com.p2elite.brtv2.R.attr.animationMode, com.p2elite.brtv2.R.attr.backgroundOverlayColorAlpha, com.p2elite.brtv2.R.attr.backgroundTint, com.p2elite.brtv2.R.attr.backgroundTintMode, com.p2elite.brtv2.R.attr.elevation, com.p2elite.brtv2.R.attr.maxActionInlineWidth};
    public static final int[] W = {com.p2elite.brtv2.R.attr.useMaterialThemeColors};
    public static final int[] X = {R.attr.icon, R.attr.layout, R.attr.text};
    public static final int[] Y = {com.p2elite.brtv2.R.attr.tabBackground, com.p2elite.brtv2.R.attr.tabContentStart, com.p2elite.brtv2.R.attr.tabGravity, com.p2elite.brtv2.R.attr.tabIconTint, com.p2elite.brtv2.R.attr.tabIconTintMode, com.p2elite.brtv2.R.attr.tabIndicator, com.p2elite.brtv2.R.attr.tabIndicatorAnimationDuration, com.p2elite.brtv2.R.attr.tabIndicatorAnimationMode, com.p2elite.brtv2.R.attr.tabIndicatorColor, com.p2elite.brtv2.R.attr.tabIndicatorFullWidth, com.p2elite.brtv2.R.attr.tabIndicatorGravity, com.p2elite.brtv2.R.attr.tabIndicatorHeight, com.p2elite.brtv2.R.attr.tabInlineLabel, com.p2elite.brtv2.R.attr.tabMaxWidth, com.p2elite.brtv2.R.attr.tabMinWidth, com.p2elite.brtv2.R.attr.tabMode, com.p2elite.brtv2.R.attr.tabPadding, com.p2elite.brtv2.R.attr.tabPaddingBottom, com.p2elite.brtv2.R.attr.tabPaddingEnd, com.p2elite.brtv2.R.attr.tabPaddingStart, com.p2elite.brtv2.R.attr.tabPaddingTop, com.p2elite.brtv2.R.attr.tabRippleColor, com.p2elite.brtv2.R.attr.tabSelectedTextColor, com.p2elite.brtv2.R.attr.tabTextAppearance, com.p2elite.brtv2.R.attr.tabTextColor, com.p2elite.brtv2.R.attr.tabUnboundedRipple};
    public static final int[] Z = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, com.p2elite.brtv2.R.attr.fontFamily, com.p2elite.brtv2.R.attr.fontVariationSettings, com.p2elite.brtv2.R.attr.textAllCaps, com.p2elite.brtv2.R.attr.textLocale};

    /* renamed from: a0, reason: collision with root package name */
    public static final int[] f11019a0 = {com.p2elite.brtv2.R.attr.textInputLayoutFocusedRectEnabled};

    /* renamed from: b0, reason: collision with root package name */
    public static final int[] f11021b0 = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, R.attr.maxEms, R.attr.minEms, com.p2elite.brtv2.R.attr.boxBackgroundColor, com.p2elite.brtv2.R.attr.boxBackgroundMode, com.p2elite.brtv2.R.attr.boxCollapsedPaddingTop, com.p2elite.brtv2.R.attr.boxCornerRadiusBottomEnd, com.p2elite.brtv2.R.attr.boxCornerRadiusBottomStart, com.p2elite.brtv2.R.attr.boxCornerRadiusTopEnd, com.p2elite.brtv2.R.attr.boxCornerRadiusTopStart, com.p2elite.brtv2.R.attr.boxStrokeColor, com.p2elite.brtv2.R.attr.boxStrokeErrorColor, com.p2elite.brtv2.R.attr.boxStrokeWidth, com.p2elite.brtv2.R.attr.boxStrokeWidthFocused, com.p2elite.brtv2.R.attr.counterEnabled, com.p2elite.brtv2.R.attr.counterMaxLength, com.p2elite.brtv2.R.attr.counterOverflowTextAppearance, com.p2elite.brtv2.R.attr.counterOverflowTextColor, com.p2elite.brtv2.R.attr.counterTextAppearance, com.p2elite.brtv2.R.attr.counterTextColor, com.p2elite.brtv2.R.attr.endIconCheckable, com.p2elite.brtv2.R.attr.endIconContentDescription, com.p2elite.brtv2.R.attr.endIconDrawable, com.p2elite.brtv2.R.attr.endIconMode, com.p2elite.brtv2.R.attr.endIconTint, com.p2elite.brtv2.R.attr.endIconTintMode, com.p2elite.brtv2.R.attr.errorContentDescription, com.p2elite.brtv2.R.attr.errorEnabled, com.p2elite.brtv2.R.attr.errorIconDrawable, com.p2elite.brtv2.R.attr.errorIconTint, com.p2elite.brtv2.R.attr.errorIconTintMode, com.p2elite.brtv2.R.attr.errorTextAppearance, com.p2elite.brtv2.R.attr.errorTextColor, com.p2elite.brtv2.R.attr.expandedHintEnabled, com.p2elite.brtv2.R.attr.helperText, com.p2elite.brtv2.R.attr.helperTextEnabled, com.p2elite.brtv2.R.attr.helperTextTextAppearance, com.p2elite.brtv2.R.attr.helperTextTextColor, com.p2elite.brtv2.R.attr.hintAnimationEnabled, com.p2elite.brtv2.R.attr.hintEnabled, com.p2elite.brtv2.R.attr.hintTextAppearance, com.p2elite.brtv2.R.attr.hintTextColor, com.p2elite.brtv2.R.attr.passwordToggleContentDescription, com.p2elite.brtv2.R.attr.passwordToggleDrawable, com.p2elite.brtv2.R.attr.passwordToggleEnabled, com.p2elite.brtv2.R.attr.passwordToggleTint, com.p2elite.brtv2.R.attr.passwordToggleTintMode, com.p2elite.brtv2.R.attr.placeholderText, com.p2elite.brtv2.R.attr.placeholderTextAppearance, com.p2elite.brtv2.R.attr.placeholderTextColor, com.p2elite.brtv2.R.attr.prefixText, com.p2elite.brtv2.R.attr.prefixTextAppearance, com.p2elite.brtv2.R.attr.prefixTextColor, com.p2elite.brtv2.R.attr.shapeAppearance, com.p2elite.brtv2.R.attr.shapeAppearanceOverlay, com.p2elite.brtv2.R.attr.startIconCheckable, com.p2elite.brtv2.R.attr.startIconContentDescription, com.p2elite.brtv2.R.attr.startIconDrawable, com.p2elite.brtv2.R.attr.startIconTint, com.p2elite.brtv2.R.attr.startIconTintMode, com.p2elite.brtv2.R.attr.suffixText, com.p2elite.brtv2.R.attr.suffixTextAppearance, com.p2elite.brtv2.R.attr.suffixTextColor};

    /* renamed from: c0, reason: collision with root package name */
    public static final int[] f11023c0 = {R.attr.textAppearance, com.p2elite.brtv2.R.attr.enforceMaterialTheme, com.p2elite.brtv2.R.attr.enforceTextAppearance};

    /* renamed from: d0, reason: collision with root package name */
    public static final int[] f11024d0 = {R.attr.textAppearance, R.attr.textColor, R.attr.padding, R.attr.layout_margin, R.attr.minWidth, R.attr.minHeight, R.attr.text, com.p2elite.brtv2.R.attr.backgroundTint};
}
